### ISSUE TITLE
VAE stdv torch abs

### ISSUE THREAD

**Issue by lfb-1** [chaoyan1037/Re-balanced-VAE#2]
Hi,

I notice that when calculating mu logvar in your VAE, you have -torch.abs(logvar) instead of directly using logvar. I never seen this operation in other vae approaches (I might be wrong?). What is the purpose of this?

Cheers

**Comment by chaoyan1037** [comment]
Hi，

Which part of the code are you referring to?

**Comment by lfb-1** [comment]
Sorry. I was talking torch.abs

>         logv = -torch.abs(self.logvar_lin(hidden))

**Comment by chaoyan1037** [comment]
```
logv = -torch.abs(self.logvar_lin(hidden))
```
It can force the variance to be within (0, 1). This trick can be found [here](https://github.com/wengong-jin/icml18-jtnn/blob/master/jtnn/jtnn_vae.py#L77).

**Comment by lfb-1** [comment]
Oh. Thanks. I will take a look
